import Head from "next/head";
import SocialMedia from "../components/SocialMedia";
import Link from "next/link";
import Image from "next/image";
import avatar from "../public/avatar.jpg";
import { whatsappURL } from "../data/user";
import services from "../data/services";
import { Service } from "../components/Service";

export default function Home() {
  return (
    <>
      <Head>
        <title>Consultoria Acadêmica</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full">
        <div
          id="inicio"
          className="flex flex-col bg-[url('../public/banner.png')] bg-cover bg-center
          text-white"
        >
          <div className="flex flex-col bg-black/50 p-4 sm:p-8 sm:px-24 gap-y-16 h-[26rem] sm:h-[40rem]">
            {/* Cabeçalho */}
            <div id="header" className="flex flex-row justify-between">
              <div id="logo">
                <p className="text-sm font-bold ">Amandha Queiroz</p>
                <p className="text-sm italic">Consultora acadêmica</p>
              </div>
              <SocialMedia />
            </div>
            {/* Banner inicial */}
            <div className="flex flex-col justify-center items-center gap-y-2 sm:items-start sm:h-full">
              <div className="text-center text-4xl tracking-wide font-extrabold sm:text-6xl">
                Consultoria Acadêmica
              </div>
              <div className="text-center font-semibold sm:text-lg">
                Orientação, revisão, formatação e construção.
              </div>
              <Link
                href="/orcamento"
                className="bg-orange-600 hover:bg-orange-700 font-semibold p-3 rounded-md font-mono uppercase mt-8"
              >
                Solicitar Orçamento
              </Link>
            </div>
          </div>
        </div>
        <div
          id="sobre"
          className="bg-white flex flex-col justify-center items-center p-8"
        >
          <div className="flex flex-col justify-start items-center gap-y-8 sm:flex-row sm:justify-center sm:gap-x-12 ">
            <Image
              alt="Avatar logo"
              src={avatar}
              className="h-40 w-40 rounded-full sm:w-60 sm:h-60"
            />
            <div>
              <p className="font-sans text-2xl font-extrabold">
                Amandha Queiroz
              </p>
              <p className="uppercase font-mono text-sm text-orange-700">
                Consultora acadêmica
              </p>
              <div className="pt-4">
                <p>Falar um pouco da sua formacao...</p>
                <p>
                  Meu principal objetivo é prover um serviço de qualidade...
                </p>
                <p>
                  Mais alguma coisa sobre a importância do serviço de
                  consultoria...
                </p>
              </div>
            </div>
          </div>
          <Link
            href={whatsappURL}
            target="_blank"
            className="text-white bg-orange-600 hover:bg-orange-700 font-semibold p-3 rounded-md font-mono uppercase mt-8
            drop-shadow-xl"
          >
            Enviar mensagem
          </Link>
        </div>
        <div id="servicos" className="py-16 px-4 sm:px-24  bg-[url('../public/banner-white.jpg')] bg-cover bg-center ">
          <div className="flex flex-col justify-center items-start gap-12 sm:flex-row">
            {services.map((s) => {
              return (
                <Service
                  key={s.name}
                  name={s.name}
                  summary={s.summary}
                  description={s.description}
                  icon={s.icon}
                />
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}
